baseURL = "https://staceykd.github.io/furina.github.io/"
locale = 'zh-cn'
title = 'My New Hugo Project'
theme = "reimu"
relativeURLs = false
canonifyURLs = true

[params]
  author = "你的名字"
  description = "记录技术与思考"
  highlight = true
