baseURL = "https://staceykd.github.io/furina.github.io/"
locale = 'zh-cn'
title = 'CTF 新手学习'
theme = "reimu"
relativeURLs = false
canonifyURLs = true

[params]
  author = "Furina"
  description = "就随便玩玩，真的能成为CTFer吗？"
  highlight = true
